[project]
name = "block-chain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.0",
    "requests>=2.32.4",
    "uvicorn[standard]>=0.35.0",
]
