/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Tree: typeof import('./components/Tree/Tree.vue')['default']
    TreeWrap: typeof import('./components/Tree/TreeWrap.vue')['default']
  }
}
