on:
  push:
    branches: [main]
    paths:
      - packages/**
  workflow_dispatch:

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm i
      - name: Test
        run: pnpm test packages
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
      - run: pnpm pub
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
